name: Test Workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Action
        uses: ./
        with:
          user: alexgocariq
          token: ${{secrets.GH_AUTH_TOKEN}}
          repo: actions-play
          workflow: pr_build
          branch: main
          group: smoke
          env: test
